package au.edu.jcu.cp3406.foleyapp;

public enum Sound
{
    BALLOON_STRETCH,
    COW_MOO, COW_SPLAT, COW_HOOVES,
    OFFICE_COPIER, OFFICE_PUNCH, OFFICE_STAPLER, OFFICE_TYPEWRITER,
    WORK_HAMMER, WORK_HANDSAW, WORK_SANDER, WORK_TABLESAW
}
